# Generated by Django 5.2.4 on 2025-08-27 14:07

from decimal import Decimal

import django.core.serializers.json
import django.db.models.deletion
import django.db.models.functions.datetime
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations
from django.db import models

import winemaking.models.action
import winemaking.types


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(editable=False)),
                ("effective_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE_VOLUME", "Receive Volume"),
                            ("BLEND", "Blend"),
                            ("REMEASURE", "Remeasure"),
                            ("BOTTLE", "Bottle"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "involved_wine_lot_ids",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(list, (str,)),
                    ),
                ),
                ("revision_number", models.PositiveIntegerField(default=0)),
                (
                    "details",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=winemaking.models.action.ActionDetails,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActionEventStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_created=True, db_default=django.db.models.functions.datetime.Now())),
                ("aggregate_id", models.CharField(db_index=True)),
                ("event_type", models.CharField()),
                ("event_data", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("sequence_number", models.CharField(null=True)),
            ],
            options={
                "ordering": ["occurred_at", models.OrderBy(models.F("sequence_number"), nulls_first=True), "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WineLot",
            fields=[
                ("id", models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(editable=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("volume", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WineLotEventStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_created=True, db_default=django.db.models.functions.datetime.Now())),
                ("aggregate_id", models.CharField(db_index=True)),
                ("event_type", models.CharField()),
                ("event_data", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("sequence_number", models.CharField(null=True)),
            ],
            options={
                "ordering": ["occurred_at", models.OrderBy(models.F("sequence_number"), nulls_first=True), "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WineLotComponent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "component",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=winemaking.types.ComponentAmount,
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wine_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="components", to="winemaking.winelot"
                    ),
                ),
            ],
        ),
    ]
